apiVersion: apps/v1
kind: Deployment
metadata:
  name: regform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regform
  template:
    metadata:
      labels:
        app: regform
    spec:
      containers:
        - name: regform
          image: regform:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: reg-service
spec:
  type: NodePort
  selector:
    app: regform
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
