apiVersion: apps/v1
kind: Deployment
metadata:
  name: reg-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reg-app
  template:
    metadata:
      labels:
        app: reg-app
    spec:
      containers:
        - name: reg-app
          image: reg-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: reg-service
spec:
  type: NodePort
  selector:
    app: reg-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
